-- Drop existing tables if they exist
DROP TABLE IF EXISTS SAVED_RESTAURANTS;

DROP TABLE IF EXISTS USERS;

-- Users table
CREATE TABLE IF NOT EXISTS USERS (
    ID UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    CLERK_ID TEXT UNIQUE NOT NULL,
    EMAIL TEXT UNIQUE,
    FIRST_NAME TEXT,
    LAST_NAME TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Saved restaurants table
CREATE TABLE IF NOT EXISTS SAVED_RESTAURANTS (
    ID UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    USER_ID UUID NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    PLACE_ID TEXT NOT NULL,
    NAME TEXT,
    IMAGE TEXT,
    RATING FLOAT,
    TYPES TEXT[],
    VICINITY TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(USER_ID, PLACE_ID)
);

-- Enable RLS (disabled for API route control)
-- ALTER TABLE users ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE saved_restaurants ENABLE ROW LEVEL SECURITY;

-- Disable RLS since we handle auth in API routes
ALTER TABLE USERS DISABLE ROW LEVEL SECURITY;

ALTER TABLE SAVED_RESTAURANTS DISABLE ROW LEVEL SECURITY;

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS IDX_SAVED_RESTAURANTS_USER_ID ON SAVED_RESTAURANTS(USER_ID);

CREATE INDEX IF NOT EXISTS IDX_SAVED_RESTAURANTS_PLACE_ID ON SAVED_RESTAURANTS(PLACE_ID);

CREATE INDEX IF NOT EXISTS IDX_USERS_CLERK_ID ON USERS(CLERK_ID);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS IDX_SAVED_RESTAURANTS_USER_ID ON SAVED_RESTAURANTS(USER_ID);

CREATE INDEX IF NOT EXISTS IDX_SAVED_RESTAURANTS_PLACE_ID ON SAVED_RESTAURANTS(PLACE_ID);